version: '3.9'

services:

    m2_database:
        hostname: m2_mysql_database
        restart: always
        container_name: m2_mysql_database

        image: mysql
        # image: mysql:latest

        # volumes:
        #     - /tmp/docker/mysql:/var/lib/mysql

        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=snapshots
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=qwerty12345

        ports:
            - 3306:3306/tcp
            - 33060:33060/tcp

        networks:
            - docker_network


networks:

    docker_network:
        name: docker_network
        driver: "bridge"