- pipeline.id: service_stamped_json_logs
  pipeline.workers: 1
  pipeline.batch.size: 1
  path.config: "/home/andtokm/DiskS/Docker/DockerCompose/LogStash/config/pipelines/service_stamped_json_logs.conf"