version: '3.9'

services:

    database:
        image: mariadb
        restart: always
        volumes:
            - ./.data/sql:/var/lib/mysql

    web:
        build:
            dockerfile: Dockerfile-alpine
            context: ./web
        ports:
            - 8099:80
        depends_on:
            - database