version: '3.9'

services:

    it_tools:
        image: corentinth/it-tools:latest
        hostname: it_tools
        restart: always
        container_name: it_tools

        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=testdb
          - MYSQL_USER=admin
          - MYSQL_DATABASE=admin

        ports:
          - 8080:80