version: '3.9'

services:

    mariadb:
        image: mariadb:10.7
        hostname: mariadb
        restart: always
        container_name: mariadb

        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=testdb
          - MYSQL_USER=admin
          - MYSQL_DATABASE=admin

        ports:
          - 3306:3306

        #volumes:
        #  - ~/apps/mariadb:/var/lib/mysql
