version: '3.9'

services:

    broker:
        hostname: mongo
        restart: always
        container_name: mongo_container
        image: mongo

        ports:
            - 27017:27017

        volumes:
        #     - /var/run/docker.sock:/var/run/docker.sock
            - /home/andtokm/DiskS/Temp/docker/mongodb:/data/db

        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
